# @package _global_
dataset:
  outcome_list:
    - diastolic blood pressure

model:

  COSO:
    optimizer:
      learning_rate: 0.001
    batch_size: 32
    seq_hidden_units: 144
    br_size: 72
    fc_hidden_units: 36
    dropout_rate: 0.4
    s_alpha: 1.0
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 256
    seq_hidden_units: 144
    br_size: 72
    fc_hidden_units: 36
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.0001
    batch_size: 256
    seq_hidden_units: 72
    br_size: 94
    fc_hidden_units: 188
    dropout_rate: 0.2

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 200
