# @package _global_
model:
  encoder:
    tune_hparams: True
    hparams_grid:
      num_layer:
        - 1
        - 2
      num_heads:
        - 2
        - 3
      learning_rate:
        - 0.01
        - 0.001
        - 0.0001
      batch_size:
        - 32
        - 64
        - 128
      seq_hidden_units:
        - 0.5
        - 1.0
        - 2.0
      br_size:
        - 0.5
        - 1.0
        - 2.0
      fc_hidden_units:
        - 0.5
        - 1.0
        - 2.0
      dropout_rate:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
    resources_per_trial:
      cpu: 0.4
      gpu: 0.25

  decoder:
    tune_hparams: True
    hparams_grid:
      num_layer:
        - 1
        - 2
      num_heads:
        - 2
        - 3
      learning_rate:
        - 0.01
        - 0.001
        - 0.0001
      batch_size:
        - 128
        - 256
        - 512
      br_size:
        - 0.5
        - 1.0
        - 2.0
      fc_hidden_units:
        - 0.5
        - 1.0
        - 2.0
      dropout_rate:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
    resources_per_trial:
      cpu: 0.5
      gpu: 0.33