# @package _global_
dataset:
  max_number: 1000

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 24
    br_size: 44
    fc_hidden_units: 22
    dropout_rate: 0.1
    num_layer: 1
    num_heads: 2

    self_positional_encoding:
      max_relative_position: 20

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 400