# @package _global_
dataset:
  coeff: 0.0

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    seq_hidden_units: 48
    br_size: 8
    fc_hidden_units: 8
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150