# @package _global_
dataset:
  _target_: src.data.SimulateDatasetCollection   # Will be dynamically instantiated
  name: tumor_generator
  seed: ${exp.seed}
  num_confounder: ${dataset.num_confounder}    
  num_u: ${dataset.num_u} 
  datasize: ${dataset.datasize}
  total_time_step: ${dataset.total_time_step}
  num_covariates: ${dataset.num_covariates} 
  split:
    val: 0.15
    test: 0.15
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  max_seq_length: 60                                    # Max length of time series
  projection_horizon: 5                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  cf_seq_mode: sliding_treatment                        # sliding_treatment / random_trajectories
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multiclass                        # multiclass / multilabel -- for RMSN
  time_step: 30
model:
  dim_treatments: 4
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 1

exp:
  unscale_rmse: True
  percentage_rmse: True
