hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      colorlog:
        (): colorlog.ColoredFormatter
        format: '[%(cyan)s%(asctime)s%(reset)s][%(purple)sHYDRA%(reset)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
      colorlog:
        (): colorlog.ColoredFormatter
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s]
          - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: red
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - +dataset=mimic3_real
    - +backbone=crn
    - +backbone/crn_hparams/mimic3_real=diastolic_blood_pressure
  job:
    name: train_enc_dec
    chdir: null
    override_dirname: +backbone/crn_hparams/mimic3_real=diastolic_blood_pressure,+backbone=crn,+dataset=mimic3_real
    id: ???
    num: ???
    config_name: config.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: D:\Mingjun\CausalTransformer
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: D:\Mingjun\CausalTransformer\config
      schema: file
      provider: main
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      backbone/crn_hparams/mimic3_real: diastolic_blood_pressure
      backbone: crn
      dataset: mimic3_real
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: colorlog
      hydra/hydra_logging: colorlog
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model:
  dim_treatments: ???
  dim_vitals: ???
  dim_static_features: ???
  dim_outcomes: ???
  name: CRN
  encoder:
    _target_: src.models.crn.CRNEncoder
    seq_hidden_units: 144
    br_size: 72
    fc_hidden_units: 36
    dropout_rate: 0.1
    num_layer: 1
    batch_size: 256
    optimizer:
      optimizer_cls: adam
      learning_rate: 0.001
      weight_decay: 0.0
      lr_scheduler: false
    tune_hparams: false
    tune_range: 50
    hparams_grid: null
    resources_per_trial: null
  train_decoder: true
  decoder:
    _target_: src.models.crn.CRNDecoder
    seq_hidden_units: null
    br_size: 94
    fc_hidden_units: 188
    dropout_rate: 0.2
    num_layer: 1
    batch_size: 256
    optimizer:
      optimizer_cls: adam
      learning_rate: 0.0001
      weight_decay: 0.0
      lr_scheduler: false
    tune_hparams: false
    tune_range: 30
    hparams_grid: null
    resources_per_trial: null
dataset:
  val_batch_size: 512
  treatment_mode: multilabel
  _target_: src.data.MIMIC3RealDatasetCollection
  seed: ${exp.seed}
  name: mimic3_real
  path: data/processed/all_hourly_data.h5
  min_seq_length: 30
  max_seq_length: 60
  max_number: 5000
  projection_horizon: 5
  split:
    val: 0.15
    test: 0.15
  autoregressive: true
  treatment_list:
  - vaso
  - vent
  outcome_list:
  - diastolic blood pressure
  vital_list:
  - heart rate
  - red blood cell count
  - sodium
  - mean blood pressure
  - systemic vascular resistance
  - glucose
  - chloride urine
  - glascow coma scale total
  - hematocrit
  - positive end-expiratory pressure set
  - respiratory rate
  - prothrombin time pt
  - cholesterol
  - hemoglobin
  - creatinine
  - blood urea nitrogen
  - bicarbonate
  - calcium ionized
  - partial pressure of carbon dioxide
  - magnesium
  - anion gap
  - phosphorous
  - venous pvo2
  - platelets
  - calcium urine
  static_list:
  - gender
  - ethnicity
  - age
  drop_first: false
exp:
  seed: 100
  gpus:
  - 0
  max_epochs: 200
  logging: true
  mlflow_uri: http://127.0.0.1:5000
  unscale_rmse: true
  percentage_rmse: false
  alpha: 1.0
  update_alpha: true
  alpha_rate: exp
  balancing: grad_reverse
  bce_weight: false
  weights_ema: false
  beta: 0.99
