# @package _global_
dataset:
  coeff: 0.0

model:
  COSO:
    optimizer:
      learning_rate: 0.01
    batch_size: 32
    seq_hidden_units: 128
    br_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    seq_hidden_units: 24
    br_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 1024
    seq_hidden_units: 3
    br_size: 18
    fc_hidden_units: 18
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 200