# @package _global_
dataset:
  num_confounder: 3
  num_u: 1
model:
  COSO:
    optimizer:
      learning_rate: 0.001
    batch_size: 32
    seq_hidden_units: 64
    br_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1
    s_alpha: 1
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 48
    br_size: 6
    fc_hidden_units: 24
    dropout_rate: 0.1

  train_decoder: False
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 1024
    seq_hidden_units: 3
    br_size: 18
    fc_hidden_units: 18
    dropout_rate: 0.1

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150
